name: 自动构建docker镜像

on:
  schedule:
    - cron: "00 12 * * 0"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: started


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 2816186861@qq.com
          password: Mm13598317435.

      - name: akile monitor client meta
        id: client_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/akile_monitor_client
          tags: |
            type=raw,value=latest
            {{date 'YYYY/MM/DD/hh/mm/ss'}}

      - name: Debug client_meta tags
        run: echo "${{ steps.client_meta.outputs.tags }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push client
        id: docker_build_client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          target: client
          tags: ${{ steps.client_meta.outputs.tags }}
          labels: ${{ steps.client_meta.outputs.labels }}

      - name: client Image digest
        run: echo ${{ steps.docker_build_client.outputs.digest }}
